# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

timezone: Asia/Kolkata
title: Moviesda
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Moviesda Tamil Movies Download Moviesda 2023 Movies Download
baseurl: "/testing" # the subpath of your site, e.g. /blog
url: "https://jayasurya.co.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima

# Filtering Content
future: true
plugins:
  - jekyll-paginate
  - jekyll-timeago
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at

paginate: 12
paginate_path: /latest-updates/:num/

collections:
  year:
    output: true
  language:
    output: true
    
defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: movie
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /movie/:title.html
  - scope:
      path: ''          # An empty string here means all files in the project
      type: year
    values:
      layout: year
      permalink: /browse-by-year/:title.html
  - scope:
      path: ''          # An empty string here means all files in the project
      type: language
    values:
      layout: language
      permalink: /browse-by-language/:title.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
